# ============================================
# Глобальные настройки для всех серверов
# ============================================
[all:vars]
ansible_user = vagrant
ansible_ssh_common_args = -o StrictHostKeyChecking=no
ansible_python_interpreter = /usr/bin/python3

# ============================================
# Группа: База данных
# ============================================
[database]
database ansible_host=192.168.56.13  ansible_ssh_private_key_file=../.vagrant/machines/database/virtualbox/private_key

# ============================================
# Группа: Веб-серверы
# ============================================
[webservers]
web1 ansible_host=192.168.56.11 ansible_ssh_private_key_file=../.vagrant/machines/web1/virtualbox/private_key
web2 ansible_host=192.168.56.12 ansible_ssh_private_key_file=../.vagrant/machines/web2/virtualbox/private_key

# ============================================
# Группа: Балансировщик
# ============================================
[loadbalancer]
balancer ansible_host=192.168.56.10 ansible_ssh_private_key_file=../.vagrant/machines/balancer/virtualbox/private_key

# ============================================
# Сборная группа: Все серверы приложения
# ============================================
[app_servers:children]
database
webservers
loadbalancer
