---
# vars/main.yml - Переменные для веб-сервера

# Данные для подключения к базе данных (должны совпадать с настройками в database.yml)
db_host: "192.168.56.13"
db_name: "myapp"
db_user: "user"
db_password: "12345678"
db_port: 5432

# Корневая директория сайта
document_root: "/var/www/html"

# Пользователь и группа для веб-сервера
web_user: "www-data"
web_group: "www-data"
