---
# handlers/main.yml - Обработчики для PostgreSQL

- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
  tags: ['service']

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded
  tags: ['service']