ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro' # Для того чтобы качать образы (box) для развертывания ОС машин.

Vagrant.configure(2) do |config|
    #config.vm.box_url = "https://example.com/mybox.box" - видел еще такой вариант для скачивания образов (боксов) с других источников 
    config.vm.box = "ubuntu/bionic64" # определили образа для всех машин
    #сonfig.vm.box_version = "20240401.0.0" - можно задать определенную версию бокса  
	
    # блок для определения настроек (характеристик) всех создаваемых VM в этом файле, только если я не переопределю их, как сделал в VM nginx. Для разных провайдеров немного разный синтаксис.         
    config.vm.provider "virtualbox" do |vb|   
		vb.memory = 512
        #vb.cpus = 2     - выделил 2 ядра для VM
        #vb.gui = false  - отключил гарафику на VM
		vb.customize ["modifyvm", :id, "--audio", "none"]
        #vb.customize ["команда", :id, "--параметр", "значение"] - утилита для настройки VM до её включения. в примере выше я отключил звуковую подсистему VM для теста и экономии ресурсов. 
	end
	
	
        # Первая машина Nginx
	config.vm.define "balancer" do |nginxbalans|
        #Задал Имя VM
		nginxbalans.vm.hostname = "balancer" 
		
        #Определение параметров сети для VM. также тут можно указать параметры:
		#host_ip: "127.0.0.1",  # слушать только localhost
		#protocol: "tcp",        # tcp или udp
		#auto_correct: true      # если порт занят, найти другой
        #В моем примере сеть приватная и грубо говоря я сделал VLAN для работы моих VM.
        #Если задать параметр public_network - в этом случае ВМ получает IP из вашей локальной сети (как обычный комп). 
        #Уточнить по поводу параметра  bridge: "en0: Wi-Fi (AirPort)" - имя интерфейса                
                
        nginxbalans.vm.network "private_network", ip: "192.168.56.10"
		nginxbalans.vm.network "forwarded_port", guest: 80, host:8080
                
        #Переопределил свои настройки для этой VM
		nginxbalans.vm. provider "virtualbox" do |vb|
			vb.memory = 1024
			vb.customize ["modifyvm", :id, "--audio", "none"] # отключили звуковую карту для VM что на тратить ресурсы. 
		end
	end 

    # Вторая машина Web-сервис_1
	config.vm.define "web1" do |web_1|
		web_1.vm.hostname = "web1"
		web_1.vm.network "private_network", ip: "192.168.56.11"
	end
	
    # Третья машина Web-сервис_2
	config.vm.define "web2" do |web_2|
		web_2.vm.hostname = "web2"
		web_2.vm.network "private_network", ip: "192.168.56.12"
	end 
	
    # Четвертая машина PostgresQL 
	config.vm.define "database" do |postgres|
		postgres.vm.hostname = "database"
		postgres.vm.network "private_network", ip: "192.168.56.13"
	end 

end 
