ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro' # Для того чтобы качать образы (box) для развертывания ОС машин.

Vagrant.configure(2) do |config|
        config.vm.box = "ubuntu/bionic64" # определили образа для всех машин 
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 512
		vb.customize ["modifyvm", :id, "--audio", "none"]
	end
	
	
        # Первая машина Nginx
	config.vm.define "balancer" do |nginxbalans|
		nginxbalans.vm.hostname = "balancer" 
		nginxbalans.vm.network "private_network", ip: "192.168.56.10"
		nginxbalans.vm.network "forwarded_port", guest: 80, host:8080
                
		nginxbalans.vm. provider "virtualbox" do |vb|
			vb.memory = 1024
			vb.customize ["modifyvm", :id, "--audio", "none"] # отключили звуковую карту для VM что на тратить ресурсы. 
		end
	end 

        # Вторая машина Web-сервис_1
	config.vm.define "web1" do |web_1|
		web_1.vm.hostname = "web1"
		web_1.vm.network "private_network", ip: "192.168.56.11"
	end
	
        # Третья машина Web-сервис_2
	config.vm.define "web2" do |web_2|
		web_2.vm.hostname = "web2"
		web_2.vm.network "private_network", ip: "192.168.56.12"
	end 
	
        # Четвертая машина PostgresQL 
	config.vm.define "database" do |postgres|
		postgres.vm.hostname = "database"
		postgres.vm.network "private_network", ip: "192.168.56.13"
	end 
		
end 
