---
# defaults/main.yml - Настройки по умолчанию

# Версия Nginx (latest = последняя стабильная)
nginx_version: latest

# Максимальное количество одновременных соединений
worker_connections: 100

# Таймауты
proxy_connect_timeout: 60s
proxy_send_timeout: 60s
proxy_read_timeout: 60s

# Размер буфера для прокси
proxy_buffer_size: 4k
proxy_buffers: 8 4k